services:
  backend:
    build: ./back
    container_name: backend
    ports:
      - "3000:3000"
    volumes:
      - ./back:/app              # Monta la carpeta local "back" dentro del contenedor
      - /app/node_modules        # Evita sobrescribir node_modules del contenedor
    networks:
      - appnet

  frontend:
    build: ./front
    container_name: frontend
    ports:
      - "4200:4200"               # Si usas ng serve
      # - "8080:80"               # Si usas Nginx
    volumes:
      - ./front:/app              # Monta la carpeta local "front" dentro del contenedor
      - /app/node_modules         # Igual que en backend
    networks:
      - appnet

networks:
  appnet:
    driver: bridge
